### ISSUE TITLE
测试vgg_16_cifar.py报错

### ISSUE THREAD

**Issue by quietsmile** [baidu/Paddle#9]
ubuntu 14.04， cuda 7.5, cudnn 5.1.5 安装成功
但是跑demo/image_classification/train.sh时报错，错误信息如下：

[INFO 2016-08-31 17:20:21,497 layers.py:1430] channels=512 size=8192
[INFO 2016-08-31 17:20:21,497 layers.py:1430] output size for __conv_8__ is 4 
[INFO 2016-08-31 17:20:21,498 layers.py:1430] channels=512 size=8192
[INFO 2016-08-31 17:20:21,499 layers.py:1430] output size for __conv_9__ is 4 
[INFO 2016-08-31 17:20:21,501 layers.py:1490] output size for __pool_3__ is 2*2 
[INFO 2016-08-31 17:20:21,502 layers.py:1490] output size for __pool_4__ is 1*1 
[INFO 2016-08-31 17:20:21,507 networks.py:960] The input order is [image, label]
[INFO 2016-08-31 17:20:21,507 networks.py:963] The output order is [__cost_0__]
I0831 17:20:21.523936 13974 Trainer.cpp:169] trainer mode: Normal
I0831 17:20:21.546594 13974 PyDataProvider2.cpp:219] loading dataprovider image_provider::processData
[INFO 2016-08-31 17:20:21,682 image_provider.py:52] Image size: 32
[INFO 2016-08-31 17:20:21,682 image_provider.py:53] Meta path: data/cifar-out/batches/batches.meta
[INFO 2016-08-31 17:20:21,682 image_provider.py:58] DataProvider Initialization finished
I0831 17:20:21.682675 13974 PyDataProvider2.cpp:219] loading dataprovider image_provider::processData
[INFO 2016-08-31 17:20:21,682 image_provider.py:52] Image size: 32
[INFO 2016-08-31 17:20:21,682 image_provider.py:53] Meta path: data/cifar-out/batches/batches.meta
[INFO 2016-08-31 17:20:21,682 image_provider.py:58] DataProvider Initialization finished
I0831 17:20:21.683006 13974 GradientMachine.cpp:134] Initing parameters..
I0831 17:20:22.312453 13974 GradientMachine.cpp:141] Init parameters done.
.........
I0831 17:20:52.894659 13974 TrainerInternal.cpp:162]  Batch=100 samples=12800 AvgCost=2.35864 CurrentCost=2.35864 Eval: classification_error_evaluator=0.833906  CurrentEval: classification_error_evaluator=0.833906 
.........
I0831 17:21:00.884374 13974 TrainerInternal.cpp:162]  Batch=200 samples=25600 AvgCost=2.15774 CurrentCost=1.95684 Eval: classification_error_evaluator=0.792148  CurrentEval: classification_error_evaluator=0.750391 
.........
I0831 17:21:08.731333 13974 TrainerInternal.cpp:162]  Batch=300 samples=38400 AvgCost=2.01417 CurrentCost=1.72705 Eval: classification_error_evaluator=0.753672  CurrentEval: classification_error_evaluator=0.676719 
.........I0831 17:21:15.873359 13974 TrainerInternal.cpp:179]  Pass=0 Batch=391 samples=50048 AvgCost=1.90795 Eval: classification_error_evaluator=0.71814 
F0831 17:21:18.497601 13974 hl_cuda_cudnn.cc:779] Check failed: CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 5) Cudnn Error: CUDNN_STATUS_INVALID_VALUE
*** Check failure stack trace: ***
    @     0x7f609f255daa  (unknown)
    @     0x7f609f255ce4  (unknown)
    @     0x7f609f2556e6  (unknown)
    @     0x7f609f258687  (unknown)
    @           0x8a98d4  hl_convolution_forward()
    @           0x5c66fc  paddle::CudnnConvLayer::forward()
    @           0x62305c  paddle::NeuralNetwork::forward()
    @           0x6b54af  paddle::Tester::testOneBatch()
    @           0x6b5dc2  paddle::Tester::testOnePeriod()
    @           0x69a28c  paddle::Trainer::trainOnePass()
    @           0x69d687  paddle::Trainer::train()
    @           0x53b0b3  main
    @     0x7f609e461ec5  (unknown)
    @           0x546695  (unknown)
    @              (nil)  (unknown)

更改cudnn版本，5.0.5， 4.0.4错误都一样~
求助！

**Comment by reyoung** [comment]
Please use command `paddle version` to print compile flag, and paste them here~~ Thanks.

**Comment by GangLiao** [comment]
Hi, Can you post your GPU type name? For instance, K40?

**Comment by quietsmile** [comment]
PaddlePaddle 0.8.0b, compiled with
    with_avx: ON
    with_gpu: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk: 

gtx titanx,   driver 352.39

**Comment by Dcocoa** [comment]
@quietsmile Hi, there is no problem when we tested on Tesla K20/K40 with cuda 7.5 and cudnn 5.1, cudnn 4.0. But we don't have gtx titanx environment and wasn't able to to replicate this problem. We will solve it later.

**Comment by wangjiangb** [comment]
I have added a change list to fix it.

**Comment by qingqing01** [comment]
@quietsmile We have fixed this problem in GTX 980, see https://github.com/baidu/Paddle/commit/341486d54ddb5d25685593ec3fda361338d68a7b .

**Comment by hedaoyuan** [comment]
Fixed #107, and close issue.
